// src/constants/nigeriaData.ts

export const NIGERIA_STATES_AND_CITIES: Record<string, string[]> = {
	Abia: ["Aba", "Umuahia", "Ohafia", "Arochukwu", "Bende"],
	Adamawa: ["Yola", "Mubi", "Jimeta", "Numan", "Ganye"],
	"Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Ikot Abasi"],
	Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Obosi"],
	Bauchi: ["Bauchi", "Azare", "Misau", "Jama'are", "Katagum"],
	Bayelsa: ["Yenagoa", "Brass", "Ogbia", "Sagbama", "Amassoma"],
	Benue: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Adoka"],
	Borno: ["Maiduguri", "Biu", "Bama", "Gwoza", "Monguno"],
	"Cross River": ["Calabar", "Ogoja", "Ikom", "Obudu", "Ugep"],
	Delta: ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor", "Oghara"],
	Ebonyi: ["Abakaliki", "Afikpo", "Onueke", "Edda", "Uburu"],
	Edo: ["Benin City", "Auchi", "Uromi", "Ekpoma", "Igarra"],
	Ekiti: ["Ado Ekiti", "Ikere Ekiti", "Oye Ekiti", "Aramoko", "Omuo"],
	Enugu: ["Enugu", "Nsukka", "Oji River", "Awgu", "Udi"],
	Gombe: ["Gombe", "Kumo", "Billiri", "Dukku", "Bajoga"],
	Imo: ["Owerri", "Orlu", "Okigwe", "Mgbidi", "Oguta"],
	Jigawa: ["Dutse", "Hadejia", "Birnin Kudu", "Gumel", "Kazaure"],
	Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Kagoro", "Birnin Gwari"],
	Kano: ["Kano", "Wudil", "Gwarzo", "Bichi", "Dambatta"],
	Katsina: ["Katsina", "Daura", "Funtua", "Malumfashi", "Mani"],
	Kebbi: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Bagudo"],
	Kogi: ["Lokoja", "Okene", "Kabba", "Idah", "Anyigba"],
	Kwara: ["Ilorin", "Offa", "Omu-Aran", "Lafiagi", "Patigi"],
	Lagos: [
		"Ikeja",
		"Lagos",
		"Lekki",
		"Victoria Island",
		"Badagry",
		"Ikorodu",
		"Epe",
		"Surulere",
		"Yaba",
		"Apapa",
	],
	Nasarawa: ["Lafia", "Keffi", "Nasarawa", "Karu", "Akwanga"],
	Niger: ["Minna", "Bida", "Suleja", "Kontagora", "Lapai"],
	Ogun: ["Abeokuta", "Ijebu Ode", "Sagamu", "Ota", "Ilaro", "Mowe"],
	Ondo: ["Akure", "Ondo City", "Owo", "Ikare", "Okitipupa"],
	Osun: ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Ila Orangun"],
	Oyo: ["Ibadan", "Ogbomosho", "Oyo", "Iseyin", "Saki"],
	Plateau: ["Jos", "Bukuru", "Pankshin", "Shendam", "Barkin Ladi"],
	Rivers: ["Port Harcourt", "Obio-Akpor", "Bonny", "Ahoada", "Okrika", "Eleme"],
	Sokoto: ["Sokoto", "Wurno", "Tambuwal", "Gwadabawa", "Bodinga"],
	Taraba: ["Jalingo", "Wukari", "Bali", "Gembu", "Mutum Biyu"],
	Yobe: ["Damaturu", "Gashua", "Potiskum", "Nguru", "Geidam"],
	Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Shinkafi"],
	FCT: ["Abuja", "Gwagwalada", "Kuje", "Bwari", "Lugbe"],
};
