export interface SubSection {
	id: string;
	title: string;
	paragraphs: string[];
	bullets: string[];
	table?: {
		headers: string[];
		rows: string[][];
	};
}

export interface PrivacySection {
	id: string;
	title: string;
	paragraphs: string[];
	bullets: string[];
	subsections: SubSection[];
}

export interface PrivacyPolicyData {
	title: string;
	preamble: string[];
	documentControl: {
		title: string;
		items: string[];
	};
	revisionHistory: {
		title: string;
		items: string[];
	};
	legalNotice: {
		title: string;
		paragraphs: string[];
	};
	sections: PrivacySection[];
}

export const privacyPolicy: PrivacyPolicyData = {
	title: "SOCIOKNACK LTD. PRIVACY POLICY",
	preamble: [],
	documentControl: {
		title: "Document Control",
		items: [
			"Item Description: SOCIOKNACK LTD. PRIVACY POLICY - Version1.0",
			"Document Owner: Socioknack  Ltd.",
			"Document Classification - Public",
			"Approved by: Board of Directors / Management",
			"Review Frequency: Annual or upon material legal or operational changes",
			"Applicable Jurisdictions: Nigeria and all jurisdictions in which Socioknack operates",
			'This Privacy Policy forms an integral part of the contractual relationship between Socioknack Technologies Ltd. ("Socioknack", "Company", "we", "our", or "us") and every individual, organisation, customer, or authorised user who accesses or uses the Socioknack Platform.',
		],
	},
	revisionHistory: {
		title: "Revision History",
		items: [
			"Version Date: July 2026",
			"Description 1.0",
			"Initial Enterprise Release: August 1, 2026",
			"Future revisions may be issued to reflect changes in legislation, technology, operational practices, security standards, or platform functionality",
			".",
		],
	},
	legalNotice: {
		title: "Legal Notice",
		paragraphs: [
			"This Privacy Policy is a legally binding document that governs the collection, use, storage, disclosure, transfer, protection, retention, and destruction of Personal Data processed by Socioknack.",
			"By accessing, registering for, or using the Services, you acknowledge that you have read, understood, and accepted the terms of this Privacy Policy.",
			"If you do not agree with this Privacy Policy, you must immediately discontinue use of the Services.",
			"Nothing contained in this Privacy Policy limits any mandatory rights granted to Data Subjects under applicable privacy legislation.",
		],
	},
	sections: [
		{
			id: "1",
			title: "PURPOSE OF THIS PRIVACY POLICY",
			paragraphs: [
				"The purpose of this Privacy Policy is to establish transparent principles governing how Socioknack processes Personal Data while delivering its sales management and revenue optimisation platform.",
				"Specifically, this Privacy Policy seeks to:",
				"Socioknack recognises that privacy is a fundamental element of trust between businesses and their customers. Accordingly, the Company is committed to implementing privacy-by-design principles throughout the lifecycle of its products and services.",
			],
			bullets: [
				"explain what information we collect;",
				"explain why such information is collected;",
				"describe how information is used;",
				"explain when information may be disclosed;",
				"explain users' legal rights;",
				"describe our security practices;",
				"establish our retention obligations;",
				"ensure compliance with applicable data protection legislation;",
				"promote transparency and accountability throughout our business operations.",
			],
			subsections: [],
		},
		{
			id: "2",
			title: "SCOPE OF THIS POLICY",
			paragraphs: [
				"This Privacy Policy applies to all products, services, software applications, mobile applications, web portals, APIs, integrations, websites, customer support channels, and associated technologies operated or controlled by Socioknack.",
				"Without limitation, this Policy applies to:",
				"This Policy also governs Personal Data collected through: www.socioknack.com⁠;",
			],
			bullets: [
				"Business Customers;",
				"Enterprise Customers;",
				"Sales Agents;",
				"Territory Managers;",
				"Company Administrators;",
				"Customer Service Personnel;",
				"Employees;",
				"Contractors;",
				"Consultants;",
				"Website Visitors;",
				"Prospective Customers;",
				"Marketing Contacts;",
				"Authorised Representatives.",
				"the Socioknack mobile application;",
				"web dashboards;",
				"customer onboarding;",
				"technical support interactions;",
				"sales demonstrations;",
				"webinars;",
				"marketing campaigns;",
				"integrations with third-party platforms.",
			],
			subsections: [],
		},
		{
			id: "3",
			title: "OUR PRIVACY COMMITMENT",
			paragraphs: [
				"Socioknack is committed to conducting all data processing activities responsibly, ethically, and lawfully. Accordingly, we are committed to the following principles:",
			],
			bullets: [],
			subsections: [
				{
					id: "3.1",
					title: "Lawfulness",
					paragraphs: [
						"We shall process Personal Data only where a lawful basis exists under applicable legislation.",
					],
					bullets: [],
				},
				{
					id: "3.2",
					title: "Fairness",
					paragraphs: [
						"We shall not process Personal Data in a manner that is unfair, deceptive, or misleading.",
					],
					bullets: [],
				},
				{
					id: "3.3",
					title: "Transparency",
					paragraphs: [
						"Individuals shall be informed of how their information is collected and processed through clear and accessible notices.",
					],
					bullets: [],
				},
				{
					id: "3.4",
					title: "Purpose Limitation",
					paragraphs: [
						"Information shall be collected solely for specified, explicit, and legitimate business purposes and shall not subsequently be processed in a manner incompatible with those purposes.",
					],
					bullets: [],
				},
				{
					id: "3.5",
					title: "Data Minimisation",
					paragraphs: [
						"We collect only the Personal Data reasonably necessary to provide our Services.",
					],
					bullets: [],
				},
				{
					id: "3.6",
					title: "Accuracy",
					paragraphs: [
						"We take reasonable steps to ensure that Personal Data remains accurate, complete, and up to date.",
					],
					bullets: [],
				},
				{
					id: "3.7",
					title: "Storage Limitation",
					paragraphs: [
						"Information shall not be retained longer than reasonably necessary or as required by law.",
					],
					bullets: [],
				},
				{
					id: "3.8",
					title: "Integrity and Confidentiality",
					paragraphs: [
						"Appropriate technical and organisational safeguards shall be implemented to protect Personal Data against unauthorised access, accidental loss, destruction, alteration, or disclosure.",
					],
					bullets: [],
				},
				{
					id: "3.9",
					title: "Accountability",
					paragraphs: [
						"Socioknack accepts responsibility for complying with applicable privacy laws and maintaining effective governance over Personal Data processing activities",
					],
					bullets: [],
				},
			],
		},
		{
			id: "4",
			title: "DEFINITIONS",
			paragraphs: [
				"For the purposes of this Privacy Policy, the following terms shall have the meanings assigned below unless the context otherwise requires:",
				'"Account" means a registered user profile created to access the Socioknack Platform.',
				'"Business Customer" means any organisation subscribing to or otherwise using the Services.',
				'"Business Data" means commercial information uploaded to the Platform, including customer records, sales activities, territories, commission structures, reports, analytics, and related operational information.',
				'"Data Controller" means the natural or legal person that determines the purposes and means of processing Personal Data.',
				'"Data Processor" means the entity processing Personal Data on behalf of a Data Controller.',
				'"Personal Data" means any information relating to an identified or identifiable natural person, including but not limited to names, email addresses, telephone numbers, identification numbers, online identifiers, device information, location information, and employment-related information.',
				'"Platform" means all software, websites, APIs, mobile applications, dashboards, databases, integrations, and associated technologies operated by Socioknack.',
				'"Processing" means any operation performed on Personal Data, including collection, recording, organisation, storage, adaptation, retrieval, consultation, use, disclosure, transmission, restriction, deletion, destruction, or any combination thereof.',
				'"Services" means all products and services provided by Socioknack through its Platform.',
				'"User" means any individual authorised to access or use the Services.',
				"This concludes Part I of the Privacy Policy. It establishes the legal framework, governance principles, and defined terms that the remainder of the document will build upon.",
				"Categories of Personal Data Collected",
			],
			bullets: [
				"Customer and Business Data",
				"Sales Agent & Employee Information",
				"Device, Technical and Usage Data",
				"Cookies & Tracking Technologies",
				"GPS and Location Data",
				"Information Received from Third Parties",
				"Data Collection During Sales Demonstrations and Support",
			],
			subsections: [],
		},
		{
			id: "5",
			title: "INFORMATION WE COLLECT",
			paragraphs: [],
			bullets: [],
			subsections: [
				{
					id: "5.1",
					title: "General Principle",
					paragraphs: [
						"Socioknack collects only information that is reasonably necessary for the operation, administration, security, improvement, and lawful delivery of the Services.",
						"The categories of information collected may vary depending on:",
						"Information collected by Socioknack falls broadly into the following categories:",
						"Nothing in this Privacy Policy shall require a User to provide information that is not reasonably necessary for the intended purpose of processing.",
					],
					bullets: [
						"The nature of your relationship with Socioknack;",
						"The Services you use;",
						"Your role within your organisation;",
						"Your device configuration;",
						"Permissions granted by you or your organisation; and",
						"Applicable legal or regulatory requirements.",
						"Personal Information;",
						"Business Information;",
						"Customer Information;",
						"Sales Activity Information;",
						"Financial Information;",
						"Technical Information;",
						"Device Information;",
						"Usage Information;",
						"Communications;",
						"Location Information; and",
						"Information obtained from Third Parties.",
					],
				},
			],
		},
		{
			id: "6",
			title: "PERSONAL INFORMATION",
			paragraphs: [
				"Depending upon the Services used, Socioknack may collect Personal Information including, but not limited to:",
				"Passwords are never stored in plain text.",
				"Passwords are encrypted using industry-recognised cryptographic standards.",
			],
			bullets: [
				"Full Name;",
				"Preferred Name;",
				"Business Email Address;",
				"Personal Email Address (where applicable);",
				"Mobile Telephone Number;",
				"Office Telephone Number;",
				"Residential Address (where required);",
				"Business Address;",
				"Job Title;",
				"Department;",
				"Employer Name;",
				"Employee Identification Number;",
				"Profile Photograph;",
				"Signature (where applicable);",
				"Date of Account Registration;",
				"Account Status;",
				"User Preferences;",
				"Language Preference;",
				"Time Zone;",
				"Authentication Credentials.",
			],
			subsections: [],
		},
		{
			id: "7",
			title: "BUSINESS INFORMATION",
			paragraphs: [
				"Where an organisation subscribes to Socioknack, we may process Business Information including:",
				"Business Information remains the property of the subscribing organisation.",
				"Except where otherwise permitted by law or contract, Socioknack shall process such information solely for the purpose of providing the Services.",
			],
			bullets: [
				"Registered Company Name;",
				"Trading Name;",
				"Business Registration Number;",
				"Tax Identification Number;",
				"Company Address;",
				"Business Email Addresses;",
				"Business Telephone Numbers;",
				"Industry Classification;",
				"Sales Territories;",
				"Branch Locations;",
				"Regional Offices;",
				"Sales Structure;",
				"Commission Structure;",
				"Organisational Hierarchy;",
				"Business Reports;",
				"Sales Performance Reports;",
				"Revenue Reports;",
				"Customer Distribution Data;",
				"Territory Assignments",
			],
			subsections: [],
		},
		{
			id: "8",
			title: "CUSTOMER DATA",
			paragraphs: [
				"One of Socioknack’s principal functions is enabling organisations to manage customer relationships. Accordingly, authorised users may upload customer information including:",
				"Customer Data is processed solely on behalf of the subscribing organisation.",
				"Socioknack does not determine how Business Customers use Customer Data and therefore may act as a Data Processor in relation to such information.",
			],
			bullets: [
				"Customer Name;",
				"Contact Person;",
				"Telephone Numbers;",
				"Email Addresses;",
				"Physical Addresses;",
				"GPS Coordinates;",
				"Business Type;",
				"Industry;",
				"Customer Category;",
				"Lead Source;",
				"Purchase History;",
				"Sales Status;",
				"Follow-up Schedule;",
				"Sales Notes;",
				"Customer Interactions;",
				"Meeting Notes;",
				"Uploaded Documents;",
				"Attachments;",
				"Customer Preferences.",
			],
			subsections: [],
		},
		{
			id: "9",
			title: "SALES AGENT INFORMATION",
			paragraphs: [
				"Where authorised by the subscribing organisation, Socioknack may process information relating to Sales Agents including:",
				"This information enables organisations to improve productivity, operational accountability and performance management.",
			],
			bullets: [
				"Name;",
				"Employee ID;",
				"Team Assignment;",
				"Territory Assignment;",
				"Supervisor;",
				"Sales Targets;",
				"Sales Performance;",
				"Commission Earnings;",
				"Attendance Information;",
				"Assigned Customers;",
				"Sales Activities;",
				"Check-in Records;",
				"Route Information;",
				"Customer Visits;",
				"Lead Conversion Rates;",
				"Performance Rankings;",
				"Training Records.",
			],
			subsections: [],
		},
		{
			id: "10",
			title: "COMMISSION INFORMATION",
			paragraphs: [
				"Because Socioknack provides commission automation functionality, we may process:",
				"Commission calculations are performed based upon configuration established by the subscribing organisation. Socioknack does not independently determine compensation policies.",
			],
			bullets: [
				"Commission Rules;",
				"Commission Rates;",
				"Bonus Structures;",
				"Performance Bonuses;",
				"Sales Incentives;",
				"Approved Commissions;",
				"Pending Commissions;",
				"Commission History;",
				"Adjustment Records;",
				"Payment Status.",
			],
			subsections: [],
		},
		{
			id: "11",
			title: "SALES ACTIVITY INFORMATION",
			paragraphs: [
				"Socioknack records operational information relating to sales processes, including:",
				"This information enables organisations to maintain visibility over their sales operations.",
			],
			bullets: [
				"Lead Creation;",
				"Lead Assignment;",
				"Lead Acceptance;",
				"Follow-up Activities;",
				"Customer Calls;",
				"Sales Visits;",
				"Product Demonstrations;",
				"Proposal Submission;",
				"Negotiation Stages;",
				"Sales Pipeline Movement;",
				"Opportunity Status;",
				"Conversion Metrics;",
				"Lost Opportunities;",
				"Closed Deals;",
				"Revenue Attribution.",
			],
			subsections: [],
		},
		{
			id: "12",
			title: "DEVICE INFORMATION",
			paragraphs: [
				"To improve reliability and security, Socioknack may automatically collects certain technical information including:",
			],
			bullets: [
				"Device Manufacturer;",
				"Device Model;",
				"Operating System;",
				"Operating System Version;",
				"Browser Type;",
				"Browser Version;",
				"Screen Resolution;",
				"IP Address;",
				"Internet Service Provider;",
				"Language Settings;",
				"Time Zone;",
				"Device Identifier;",
				"Application Version;",
				"Crash Reports;",
				"Diagnostic Logs.",
				"Such information assists in:",
				"Troubleshooting;",
				"Fraud detection;",
				"Platform optimisation;",
				"Security monitoring;",
				"Software maintenance.",
			],
			subsections: [],
		},
		{
			id: "13",
			title: "USAGE INFORMATION",
			paragraphs: [
				"We automatically collect information regarding how users interact with the Services.",
				"Examples include:",
				"Usage information assists Socioknack in continuously improving usability and platform performance.",
			],
			bullets: [
				"Login Time;",
				"Logout Time;",
				"Session Duration;",
				"Pages Accessed;",
				"Dashboard Usage;",
				"Reports Generated;",
				"Searches Performed;",
				"Click Activity;",
				"Navigation Patterns;",
				"API Requests;",
				"Mobile Application Usage;",
				"Feature Adoption;",
				"User Preferences.",
			],
			subsections: [],
		},
		{
			id: "14",
			title: "LOCATION INFORMATION",
			paragraphs: [
				"Where enabled by the subscribing organisation and authorised by the user, Socioknack may collect:",
				"Location services may be disabled by the user where permitted by organisational policy and applicable law. Certain platform features may be unavailable if location access is restricted.",
			],
			bullets: [
				"GPS Coordinates;",
				"Check-in Locations;",
				"Customer Visit Locations;",
				"Sales Territory Verification;",
				"Route Information;",
				"Time of Visit;",
				"Device Location;",
				"Geofencing Events.",
				"Location data assists organisations in:",
				"Validating field visits;",
				"Confirming territory compliance;",
				"Improving workforce accountability;",
				"Reducing fraudulent reporting;",
				"Enhancing operational efficiency.",
			],
			subsections: [],
		},
		{
			id: "15",
			title: "COOKIES AND TRACKING TECHNOLOGIES",
			paragraphs: [
				"Socioknack uses cookies, pixels, web beacons, local storage technologies, and similar mechanisms to:",
				"Users may configure browser settings to refuse certain cookies. However, disabling essential cookies may affect the availability or functionality of the Services.",
			],
			bullets: [
				"Authenticate users;",
				"Maintain active sessions;",
				"Remember preferences;",
				"Improve user experience;",
				"Analyse usage trends;",
				"Secure the platform;",
				"Detect suspicious activity;",
				"Enhance platform performance.",
				"Cookies may be classified as:",
				"Essential Cookies;",
				"Functional Cookies;",
				"Performance Cookies;",
				"Analytics Cookies;",
				"Security Cookies;",
				"Preference Cookies.",
			],
			subsections: [],
		},
		{
			id: "16",
			title: "INFORMATION RECEIVED FROM THIRD PARTIES",
			paragraphs: [
				"Socioknack may receive information from authorised third-party sources, including:",
				"Information received from third parties shall be processed in accordance with this Privacy Policy and applicable law.",
			],
			bullets: [
				"Identity verification providers;",
				"Payment service providers;",
				"Customer relationship management platforms;",
				"Enterprise resource planning systems;",
				"Marketing platforms;",
				"Email service providers;",
				"Cloud hosting providers;",
				"Single sign-on providers;",
				"Publicly available business directories;",
				"Integration partners authorised by the customer.",
			],
			subsections: [],
		},
		{
			id: "17",
			title: "LEGAL BASES FOR PROCESSING PERSONAL DATA",
			paragraphs: [],
			bullets: [],
			subsections: [
				{
					id: "17.1",
					title: "General Principle",
					paragraphs: [
						"Socioknack shall process Personal Data only where a valid legal basis exists under applicable data protection legislation.",
						"Depending upon the nature of the Services, Personal Data may be processed under one or more of the following lawful bases:",
						"a. Consent of the Data Subject;",
						"b. Performance of a Contract;",
						"c. Compliance with a Legal Obligation;",
						"d. Protection of Vital Interests;",
						"e. Performance of a Task carried out in the Public Interest (where applicable);",
						"f. Legitimate Interests pursued by Socioknack or its Business Customers, provided such interests do not override the rights and freedoms of the Data Subject.",
						"Where multiple lawful bases apply, Socioknack may rely upon more than one basis simultaneously.",
					],
					bullets: [],
				},
			],
		},
		{
			id: "18",
			title: "PROCESSING BASED ON CONSENT",
			paragraphs: [
				"Where processing is based upon consent, Socioknack shall ensure that such consent is:",
				"Consent may be obtained electronically through:",
				"Withdrawal of consent shall not affect the lawfulness of processing undertaken prior to such withdrawal.",
				"Where consent is withdrawn, Socioknack may continue processing Personal Data where another lawful basis exists.",
			],
			bullets: [
				"freely given;",
				"specific;",
				"informed;",
				"unambiguous; and",
				"capable of being withdrawn at any time.",
				"account registration;",
				"cookie preference banners;",
				"application permissions;",
				"location access prompts;",
				"marketing subscription forms;",
				"electronic acknowledgements; or",
				"other lawful consent mechanisms.",
			],
			subsections: [],
		},
		{
			id: "19",
			title: "PROCESSING NECESSARY FOR CONTRACT PERFORMANCE",
			paragraphs: [
				"Socioknack processes Personal Data where such processing is necessary to perform contractual obligations owed to:",
				"Such processing includes:",
				"Failure to provide information necessary for contract performance may limit or prevent access to certain Services.",
			],
			bullets: [
				"Business Customers;",
				"Enterprise Customers;",
				"Authorised Users;",
				"Sales Agents;",
				"Contractors; and",
				"Integration Partners.",
				"account creation;",
				"user authentication;",
				"licence management;",
				"customer support;",
				"commission calculations;",
				"lead management;",
				"territory management;",
				"sales reporting;",
				"notification services;",
				"system administration.",
			],
			subsections: [],
		},
		{
			id: "20",
			title: "PROCESSING TO COMPLY WITH LEGAL OBLIGATIONS",
			paragraphs: [
				"Socioknack may process Personal Data where necessary to comply with legal or regulatory obligations, including but not limited to:",
				"Nothing in this Privacy Policy shall require Socioknack to disclose information where such disclosure would be unlawful or prohibited by a valid contractual confidentiality obligation.",
			],
			bullets: [
				"court orders;",
				"regulatory directives;",
				"tax obligations;",
				"anti-money laundering requirements;",
				"fraud investigations;",
				"cybersecurity reporting obligations;",
				"law enforcement requests made in accordance with applicable law;",
				"judicial proceedings;",
				"dispute resolution processes.",
			],
			subsections: [],
		},
		{
			id: "21",
			title: "LEGITIMATE INTERESTS",
			paragraphs: [
				"Socioknack may process Personal Data where such processing is necessary for legitimate business interests, including:",
				"Prior to relying on legitimate interests, Socioknack shall consider whether the interests, rights and freedoms of the affected individuals outweigh such legitimate interests.",
			],
			bullets: [
				"improving the Platform;",
				"preventing fraud;",
				"maintaining information security;",
				"protecting business continuity;",
				"analysing product usage;",
				"improving customer experience;",
				"developing new features;",
				"conducting internal audits;",
				"measuring platform performance;",
				"responding to customer enquiries;",
				"enforcing contractual rights.",
			],
			subsections: [],
		},
		{
			id: "22",
			title: "PURPOSES FOR WHICH PERSONAL DATA IS USED",
			paragraphs: [
				"Personal Data collected through the Services may be used for one or more of the following purposes:",
				"Socioknack shall not process Personal Data for purposes materially incompatible with those described in this Policy without an appropriate lawful basis.",
			],
			bullets: [
				"creating user accounts;",
				"authenticating users;",
				"managing subscriptions;",
				"assigning territories;",
				"tracking sales activities;",
				"automating commissions;",
				"measuring performance;",
				"monitoring field activities;",
				"generating reports;",
				"managing customer relationships;",
				"maintaining audit trails;",
				"detecting fraud;",
				"protecting the security of the Platform;",
				"improving system performance;",
				"providing customer support;",
				"communicating service announcements;",
				"sending security alerts;",
				"fulfilling contractual obligations;",
				"complying with legal obligations.",
			],
			subsections: [],
		},
		{
			id: "23",
			title: "DATA ACCURACY",
			paragraphs: [
				"Socioknack recognises that accurate information is essential to the effective operation of the Platform.",
				"Accordingly:",
			],
			bullets: [
				"Users are responsible for ensuring information they submit is accurate and complete.",
				"Business Customers shall maintain accurate customer records.",
				"Administrators shall promptly update inaccurate information.",
				"Users may request correction of inaccurate Personal Data.",
				"Socioknack shall take reasonable steps to rectify information shown to be inaccurate.",
			],
			subsections: [],
		},
		{
			id: "24",
			title: "DATA MINIMISATION",
			paragraphs: [
				"Socioknack adheres to the principle of data minimisation.",
				"Accordingly:",
				"Business Customers are encouraged to upload only information necessary for legitimate business purposes.",
			],
			bullets: [
				"only information reasonably necessary for the intended purpose shall be collected;",
				"unnecessary Personal Data shall not knowingly be requested;",
				"optional fields shall be identified where practicable;",
				"excessive or irrelevant information shall not intentionally be retained.",
			],
			subsections: [],
		},
		{
			id: "25",
			title: "AUTOMATED PROCESSING AND ARTIFICIAL INTELLIGENCE",
			paragraphs: [
				"Certain features of the Socioknack Platform may utilise automated technologies to improve operational efficiency.",
				"Examples include:",
				"Where automated decision-making significantly affects an individual, Socioknack shall endeavour to provide meaningful information regarding the logic involved, subject to applicable law and protection of proprietary algorithms.",
				"Socioknack does not intentionally use artificial intelligence to make solely automated decisions that produce legal or similarly significant effects on individuals without appropriate human oversight, unless expressly permitted by applicable law.",
			],
			bullets: [
				"automated commission calculations;",
				"automated workflow routing;",
				"lead prioritisation;",
				"task reminders;",
				"performance analytics;",
				"sales forecasting;",
				"notification scheduling.",
			],
			subsections: [],
		},
		{
			id: "26",
			title: "MARKETING COMMUNICATIONS",
			paragraphs: [
				"Socioknack may send communications relating to:",
				"Where required by law, such communications shall be sent only with the recipient's consent.",
				"Recipients may unsubscribe from non-essential marketing communications at any time by:",
				"Operational and security communications are considered essential to the provision of the Services and may continue notwithstanding marketing preferences.",
			],
			bullets: [
				"product updates;",
				"feature releases;",
				"webinars;",
				"newsletters;",
				"training opportunities;",
				"service announcements;",
				"promotional campaigns;",
				"surveys;",
				"customer success stories.",
				"clicking the unsubscribe link;",
				"updating account preferences; or",
				"contacting info@socioknack.com.",
			],
			subsections: [],
		},
		{
			id: "27",
			title: "ENTERPRISE CUSTOMER RESPONSIBILITIES",
			paragraphs: [
				"Business Customers and Enterprise Customers remain responsible for ensuring that Personal Data uploaded to the Platform has been lawfully obtained.",
				"Accordingly, each Business Customer represents and warrants that it has:",
				"Socioknack shall not be responsible for unlawful collection or disclosure of information by Business Customers before such information is uploaded to the Platform.",
			],
			bullets: [
				"an appropriate legal basis for processing;",
				"obtained all necessary consents where required;",
				"provided legally required privacy notices;",
				"complied with applicable employment laws;",
				"complied with applicable consumer protection laws;",
				"complied with applicable data protection legislation.",
			],
			subsections: [],
		},
		{
			id: "28",
			title: "ROLE OF SOCIOKNACK AS CONTROLLER AND PROCESSOR",
			paragraphs: [
				"Depending upon the circumstances, Socioknack may act as either:",
				"Where Socioknack determines the purposes and means of processing Personal Data relating to its own operations, including user accounts, billing, support, marketing, security, and platform administration.",
				"Where Socioknack processes Customer Data and Business Data solely on documented instructions from a Business Customer.",
				"When acting as a Data Processor, Socioknack shall process Personal Data only in accordance with applicable agreements and the documented instructions of the relevant Business Customer, except where otherwise required by law.",
			],
			bullets: ["(a) Data Controller", "(b) Data Processor"],
			subsections: [],
		},
		{
			id: "29",
			title: "INFORMATION SECURITY",
			paragraphs: [],
			bullets: [],
			subsections: [
				{
					id: "29.1",
					title: "Security Commitment",
					paragraphs: [
						"Socioknack recognises that information security is fundamental to maintaining the confidentiality, integrity, availability, and resilience of the Services. Accordingly, Socioknack is committed to implementing and maintaining appropriate administrative, technical, organisational, and physical safeguards designed to protect Personal Data and Business Data from unauthorised or unlawful processing, accidental loss, destruction, alteration, disclosure, or damage.",
						"Our security programme is risk-based and evolves in response to changes in technology, regulatory requirements, cybersecurity threats, and business operations.",
					],
					bullets: [],
				},
				{
					id: "29.2",
					title: "Security Governance",
					paragraphs: [
						"Socioknack shall establish and maintain an information security governance framework that includes:",
						"The Company shall periodically review its security programme to ensure that it remains appropriate for the nature, scope, and complexity of the Services.",
					],
					bullets: [
						"Security policies and standards;",
						"Internal security procedures;",
						"Defined security roles and responsibilities;",
						"Risk assessment processes;",
						"Security awareness and training programmes;",
						"Continuous monitoring and periodic review of security controls;",
						"Vendor and third-party security assessments where appropriate.",
					],
				},
			],
		},
		{
			id: "30",
			title: "TECHNICAL SECURITY MEASURES",
			paragraphs: [
				"To safeguard information processed through the Platform, Socioknack may implement security measures including, but not limited to:",
				"Security measures shall be reviewed periodically to reflect evolving industry practices.",
			],
			bullets: [
				"Encryption of data in transit using industry-standard Transport Layer Security (TLS);",
				"Encryption of sensitive credentials and authentication data;",
				"Secure application programming interfaces (APIs);",
				"Role-based access controls;",
				"Secure session management;",
				"Password hashing using recognised cryptographic algorithms;",
				"Firewall protection;",
				"Intrusion detection and prevention mechanisms;",
				"Security event logging;",
				"Malware protection;",
				"Vulnerability scanning;",
				"Security patch management;",
				"Secure cloud infrastructure;",
				"Endpoint protection;",
				"Network segmentation where appropriate.",
			],
			subsections: [],
		},
		{
			id: "31",
			title: "IDENTITY AND ACCESS MANAGEMENT",
			paragraphs: [
				"Access to Personal Data shall be restricted to individuals who require such access to perform their authorised responsibilities.",
				"Socioknack shall implement appropriate access management procedures including:",
				"Business Customers are responsible for managing the access rights of users within their organisations.",
			],
			bullets: [
				"User authentication;",
				"Unique user credentials;",
				"Role-based permissions;",
				"Least-privilege access principles;",
				"Segregation of duties where appropriate;",
				"Periodic review of user access rights;",
				"Prompt revocation of access upon termination of employment, contract, or user authorisation.",
			],
			subsections: [],
		},
		{
			id: "32",
			title: "PASSWORD SECURITY",
			paragraphs: [
				"Users are responsible for maintaining the confidentiality of their account credentials.",
				"Users agree to:",
				"Socioknack reserves the right to require password changes where account security may have been compromised.",
			],
			bullets: [
				"Create strong and unique passwords;",
				"Protect passwords from unauthorised disclosure;",
				"Refrain from sharing credentials with third parties;",
				"Promptly notify Socioknack of suspected unauthorised access or credential compromise;",
				"Update passwords periodically where required by organisational policy.",
			],
			subsections: [],
		},
		{
			id: "33",
			title: "MULTI-FACTOR AUTHENTICATION",
			paragraphs: [
				'Where available, Socioknack strongly encourages the use of Multi-Factor Authentication ("MFA") to provide an additional layer of account security.',
				"Enterprise Customers may require MFA for administrators or all users through administrative settings.",
				"Failure to enable MFA may increase the risk of unauthorised access, for which Socioknack shall not be responsible where such access results from user failure to adopt available security features.",
			],
			bullets: [],
			subsections: [],
		},
		{
			id: "34",
			title: "AUDIT LOGGING",
			paragraphs: [
				"To support accountability, security investigations, and compliance, Socioknack may maintain audit logs relating to Platform activities.",
				"Audit logs may include:",
				"Audit logs are maintained for security, operational, and compliance purposes and shall be retained in accordance with Socioknack's Data Retention Policy.",
			],
			bullets: [
				"User logins and logouts;",
				"Account creation and deletion;",
				"Password changes;",
				"Permission changes;",
				"Data exports;",
				"Administrative actions;",
				"API activity;",
				"Security events;",
				"System configuration changes;",
				"Record modifications;",
				"Failed authentication attempts.",
			],
			subsections: [],
		},
		{
			id: "35",
			title: "MONITORING AND THREAT DETECTION",
			paragraphs: [
				"Socioknack may monitor systems, networks, and applications for the purpose of detecting:",
				"Monitoring activities shall be conducted solely for legitimate security and operational purposes and in accordance with applicable law.",
			],
			bullets: [
				"Unauthorised access;",
				"Malware infections;",
				"Suspicious login attempts;",
				"Denial-of-service attacks;",
				"Credential abuse;",
				"Data exfiltration;",
				"Insider threats;",
				"Fraudulent activities;",
				"Platform misuse.",
			],
			subsections: [],
		},
		{
			id: "36",
			title: "CONFIDENTIALITY",
			paragraphs: [
				"Socioknack acknowledges that information processed through the Platform may include confidential business information, commercially sensitive data, trade secrets, customer records, and proprietary information.",
				"Accordingly:",
				"Users likewise agree to maintain the confidentiality of information accessed through the Platform and shall not disclose such information to unauthorised persons.",
			],
			bullets: [
				"Employees shall be subject to confidentiality obligations;",
				"Contractors and consultants may be required to execute confidentiality agreements;",
				"Access to confidential information shall be restricted on a need-to-know basis;",
				"Confidential information shall not be disclosed except as authorised by the applicable customer, required by law, or otherwise permitted under contractual arrangements.",
			],
			subsections: [],
		},
		{
			id: "37",
			title: "SECURITY INCIDENT RESPONSE",
			paragraphs: [
				"Socioknack shall maintain an incident response capability designed to identify, investigate, contain, remediate, and document actual or suspected security incidents.",
				"Incident response procedures may include:",
				"Incident response procedures shall be reviewed and updated periodically.",
			],
			bullets: [
				"Identification of the incident;",
				"Initial risk assessment;",
				"Containment measures;",
				"Preservation of evidence;",
				"Investigation;",
				"Root cause analysis;",
				"Corrective actions;",
				"Recovery procedures;",
				"Internal reporting;",
				"Customer communication where appropriate;",
				"Post-incident review.",
			],
			subsections: [],
		},
		{
			id: "38",
			title: "PERSONAL DATA BREACH NOTIFICATION",
			paragraphs: [
				"In the event of a Personal Data Breach, Socioknack shall assess the nature, scope, and potential impact of the incident.",
				"Where required by applicable law, Socioknack shall notify:",
				"Notifications may include:",
				"Nothing in this section shall require disclosure of information that could compromise ongoing security investigations or increase security risks.",
			],
			bullets: [
				"Competent regulatory authorities;",
				"Affected Business Customers;",
				"Impacted Data Subjects, within the timeframes prescribed by applicable legislation.",
				"Nature of the breach;",
				"Categories of information affected;",
				"Likely consequences;",
				"Measures taken or proposed;",
				"Recommended actions for affected individuals;",
				"Contact information for further enquiries.",
			],
			subsections: [],
		},
		{
			id: "39",
			title: "BUSINESS CONTINUITY AND DISASTER RECOVERY",
			paragraphs: [
				"Socioknack shall maintain reasonable business continuity and disaster recovery measures designed to minimise service disruption and facilitate recovery following significant operational incidents.",
				"Such measures may include:",
				"Recovery objectives may vary depending on service tier, infrastructure, and operational circumstances.",
			],
			bullets: [
				"Regular data backups;",
				"Redundant infrastructure where appropriate;",
				"Disaster recovery planning;",
				"System restoration procedures;",
				"Periodic recovery testing;",
				"Operational resilience planning.",
			],
			subsections: [],
		},
		{
			id: "40",
			title: "SECURITY TESTING",
			paragraphs: [
				"To maintain the security of the Platform, Socioknack may conduct or commission:",
				"Where vulnerabilities are identified, Socioknack shall seek to implement appropriate remediation measures within a commercially reasonable timeframe, taking into account the severity of the identified risk.",
			],
			bullets: [
				"Vulnerability assessments;",
				"Penetration testing;",
				"Security audits;",
				"Code reviews;",
				"Infrastructure assessments;",
				"Configuration reviews;",
				"Third-party security assessments.",
			],
			subsections: [],
		},
		{
			id: "41",
			title: "DATA RETENTION",
			paragraphs: [],
			bullets: [],
			subsections: [
				{
					id: "41.1",
					title: "General Principle",
					paragraphs: [
						"Socioknack shall retain Personal Data only for as long as necessary to fulfil the purposes for which such data was collected, to provide the Services, comply with applicable legal and regulatory obligations, resolve disputes, enforce contractual rights, and protect legitimate business interests.",
						"Retention periods shall be determined based on:",
						"Where no longer required, Personal Data shall be securely deleted, anonymised, or archived in accordance with this Policy.",
					],
					bullets: [
						"The nature of the Personal Data;",
						"The purpose of processing;",
						"Applicable contractual obligations;",
						"Statutory and regulatory requirements;",
						"Business continuity requirements;",
						"Litigation and dispute resolution needs.",
					],
				},
				{
					id: "41.2",
					title: "Indicative Retention Schedule",
					paragraphs: [
						"Unless a longer period is required by law or contract, Socioknack may retain information in accordance with the following guidelines:",
						"The foregoing periods are indicative and may be extended where necessary for legal proceedings, regulatory investigations, or legitimate business purposes.",
					],
					bullets: [],
					table: {
						headers: ["Data Category", "Typical Retention Period"],
						rows: [
							[
								"User Account Information",
								"Duration of the account plus up to 24 months after closure",
							],
							[
								"Customer Records",
								"As determined by the Business Customer or contractual obligations",
							],
							["Sales Activities", "Up to 7 years"],
							["Commission Records", "Up to 7 years"],
							["Audit Logs", "12–36 months"],
							["Technical Logs", "Up to 12 months"],
							["Support Tickets", "Up to 5 years"],
							["Billing Records", "As required by applicable tax and financial laws"],
							["Marketing Preferences", "Until withdrawn or no longer required"],
							[
								"Security Incident Records",
								"As necessary for legal, security, and compliance purposes",
							],
						],
					},
				},
			],
		},
		{
			id: "42",
			title: "SECURE DELETION AND DISPOSAL",
			paragraphs: [
				"Where Personal Data is no longer required, Socioknack shall implement reasonable measures to securely dispose of such information.",
				"Depending on the nature of the information, disposal methods may include:",
				"Backup systems may retain deleted information for a limited period before routine overwriting occurs.",
			],
			bullets: [
				"Secure deletion from production systems;",
				"Cryptographic erasure where appropriate;",
				"Secure destruction of physical media;",
				"Overwriting of storage media;",
				"Anonymisation or pseudonymisation;",
				"Secure archival in accordance with legal obligations.",
			],
			subsections: [],
		},
		{
			id: "43",
			title: "INTERNATIONAL DATA TRANSFERS",
			paragraphs: [
				"Socioknack may process or store Personal Data using infrastructure located in jurisdictions outside the country in which the data was originally collected.",
				"Where such transfers occur, Socioknack shall implement appropriate safeguards designed to ensure an adequate level of protection, which may include:",
				"International transfers shall be conducted in accordance with applicable data protection legislation, including the Nigeria Data Protection Act (NDPA), the Nigeria Data Protection Regulation (NDPR), the General Data Protection Regulation (GDPR), and other applicable laws.",
			],
			bullets: [
				"Standard contractual clauses;",
				"Data processing agreements;",
				"Adequacy decisions where available;",
				"Technical and organisational safeguards;",
				"Encryption during transmission and storage;",
				"Access controls and security monitoring.",
			],
			subsections: [],
		},
		{
			id: "44",
			title: "RIGHTS OF DATA SUBJECTS",
			paragraphs: [
				"Subject to applicable law, Data Subjects may have one or more of the following rights:",
			],
			bullets: [],
			subsections: [
				{
					id: "44.1",
					title: "Right of Access",
					paragraphs: [
						"To request confirmation as to whether Socioknack processes Personal Data relating to them and to obtain access to such information.",
					],
					bullets: [],
				},
				{
					id: "44.2",
					title: "Right to Rectification",
					paragraphs: [
						"To request correction of inaccurate or incomplete Personal Data.",
					],
					bullets: [],
				},
				{
					id: "44.3",
					title: "Right to Erasure",
					paragraphs: [
						"To request deletion of Personal Data where retention is no longer necessary or where applicable legal grounds exist.",
					],
					bullets: [],
				},
				{
					id: "44.4",
					title: "Right to Restrict Processing",
					paragraphs: [
						"To request that processing be temporarily restricted under circumstances recognised by applicable law.",
					],
					bullets: [],
				},
				{
					id: "44.5",
					title: "Right to Data Portability",
					paragraphs: [
						"Where technically feasible and legally applicable, to receive Personal Data in a structured, commonly used, and machine-readable format or to request transmission to another controller.",
					],
					bullets: [],
				},
				{
					id: "44.6",
					title: "Right to Object",
					paragraphs: [
						"To object to processing based on legitimate interests or for direct marketing purposes.",
					],
					bullets: [],
				},
				{
					id: "44.7",
					title: "Right to Withdraw Consent",
					paragraphs: [
						"Where processing is based on consent, to withdraw such consent at any time without affecting the lawfulness of processing undertaken before withdrawal.",
					],
					bullets: [],
				},
				{
					id: "44.8",
					title: "Right to Lodge a Complaint",
					paragraphs: [
						"To lodge a complaint with the relevant supervisory or regulatory authority if the individual believes that their privacy rights have been infringed.",
					],
					bullets: [],
				},
			],
		},
		{
			id: "45",
			title: "EXERCISING PRIVACY RIGHTS",
			paragraphs: [
				"Requests relating to privacy rights may be submitted by contacting:",
				"Privacy Office\nSocioknack Ltd.\nEmail: info@socioknack.com\nWebsite: www.socioknack.com",
				"To protect Personal Data, Socioknack may require reasonable verification of identity before responding to any request.",
				"Socioknack reserves the right to decline requests that are manifestly unfounded, excessive, repetitive, or otherwise not required by applicable law.",
			],
			bullets: [],
			subsections: [],
		},
		{
			id: "46",
			title: "THIRD-PARTY SERVICE PROVIDERS",
			paragraphs: [
				"Socioknack may engage trusted third-party providers to support the operation of the Services.",
				"These providers may include:",
				"Where third parties process Personal Data on behalf of Socioknack, appropriate contractual obligations shall be implemented to ensure the confidentiality, integrity, and security of such information.",
			],
			bullets: [
				"Cloud hosting providers;",
				"Payment processors;",
				"Email delivery platforms;",
				"Customer support providers;",
				"Analytics providers;",
				"Identity verification providers;",
				"Security monitoring providers;",
				"Mapping and geolocation services;",
				"Communications service providers.",
			],
			subsections: [],
		},
		{
			id: "47",
			title: "SUBPROCESSORS",
			paragraphs: [
				"Where Socioknack acts as a Data Processor, the Company may appoint qualified subprocessors to assist in delivering the Services.",
				"Socioknack shall:",
				"A current list of authorised subprocessors may be made available to Business Customers upon request or through the Socioknack website.",
			],
			bullets: [
				"Exercise reasonable care in selecting subprocessors;",
				"Require subprocessors to implement appropriate security measures;",
				"Require confidentiality obligations;",
				"Require compliance with applicable data protection legislation;",
				"Remain responsible for the performance of subprocessors to the extent required by applicable law or contract.",
			],
			subsections: [],
		},
		{
			id: "48",
			title: "GOVERNMENT, REGULATORY, AND LAW ENFORCEMENT REQUESTS",
			paragraphs: [
				"Socioknack may disclose Personal Data where disclosure is:",
				"Where legally permissible, Socioknack may notify the affected Business Customer or Data Subject before disclosing Personal Data.",
				"Nothing in this Policy shall require Socioknack to disclose information where doing so would violate applicable law or compromise ongoing investigations.",
			],
			bullets: [
				"Required by law;",
				"Required pursuant to a valid court order;",
				"Requested by a competent regulatory authority;",
				"Necessary to investigate fraud or criminal activity;",
				"Required to protect the rights, property, or safety of Socioknack, its users, or the public.",
			],
			subsections: [],
		},
		{
			id: "49",
			title: "REGULATORY COMPLIANCE",
			paragraphs: [
				"Socioknack is committed to maintaining compliance with applicable privacy and data protection legislation, including:",
				"Compliance efforts may include:",
			],
			bullets: [
				"Nigeria Data Protection Act (NDPA) 2023;",
				"Nigeria Data Protection Regulation (NDPR);",
				"General Data Protection Regulation (GDPR), where applicable;",
				"UK GDPR, where applicable;",
				"Other applicable privacy legislation in jurisdictions where the Services are offered.",
				"Periodic privacy reviews;",
				"Data protection impact assessments where appropriate;",
				"Security audits;",
				"Staff training;",
				"Policy reviews;",
				"Vendor due diligence;",
				"Internal compliance monitoring.",
			],
			subsections: [],
		},
		{
			id: "50",
			title: "COMPLAINTS",
			paragraphs: [
				"Individuals who believe that their Personal Data has been processed in violation of this Privacy Policy are encouraged to contact Socioknack in the first instance.",
				"Socioknack shall investigate complaints in good faith and seek to respond within a reasonable period, taking into account the complexity of the matter and applicable legal requirements.",
				"Nothing in this section limits the right of any individual to refer a complaint to a competent supervisory authority or to pursue any remedy available under applicable law.",
			],
			bullets: [],
			subsections: [
				{
					id: "51.2",
					title: "Ownership of Customer Data",
					paragraphs: [
						"Except as expressly provided under applicable law or contract:",
						"Socioknack acquires no ownership interest in Customer Data solely by reason of hosting, storing, processing, analysing, transmitting, or backing up such information.",
					],
					bullets: [
						"Business Customers retain ownership of Customer Data uploaded to the Platform.",
						"Sales records remain the property of the subscribing organisation.",
						"Customer contact information remains under the control of the Business Customer.",
						"Commission configurations remain the property of the Business Customer.",
						"Revenue information remains the property of the Business Customer.",
					],
				},
				{
					id: "51.3",
					title: "Platform Improvements",
					paragraphs: [
						"Business Customers acknowledge that Socioknack may generate aggregated, anonymised, or de-identified information derived from Platform usage for purposes including:",
						"Such information shall not identify any individual, organisation, or customer.",
					],
					bullets: [
						"improving the Services;",
						"benchmarking platform performance;",
						"developing new functionality;",
						"identifying industry trends;",
						"producing statistical reports.",
					],
				},
			],
		},
		{
			id: "52",
			title: "CONFIDENTIAL BUSINESS INFORMATION",
			paragraphs: [
				"Users acknowledge that information processed through the Platform may constitute confidential business information, including:",
				"Socioknack shall exercise commercially reasonable efforts to maintain the confidentiality of such information and shall not disclose it except:",
			],
			bullets: [
				"pricing structures;",
				"sales strategies;",
				"customer databases;",
				"commission structures;",
				"financial forecasts;",
				"territory assignments;",
				"product roadmaps;",
				"internal reports;",
				"operational methodologies.",
				"with customer authorisation;",
				"where required by law;",
				"to authorised subprocessors under confidentiality obligations;",
				"to protect legal rights;",
				"to investigate fraud or security incidents.",
			],
			subsections: [],
		},
		{
			id: "53",
			title: "LIMITATION OF LIABILITY",
			paragraphs: [
				"To the fullest extent permitted by applicable law:",
				"Nothing in this Policy excludes liability where such exclusion is prohibited by applicable law.",
			],
			bullets: [
				"Socioknack shall not be liable for indirect, incidental, consequential, exemplary, punitive, or special damages arising from the processing of Personal Data.",
				"Socioknack shall not be responsible for losses arising from inaccurate information supplied by Users or Business Customers.",
				"Socioknack shall not be liable for unauthorised access resulting from compromised user credentials where reasonable security measures have been provided.",
				"Socioknack shall not be liable for interruptions caused by telecommunications failures, internet outages, force majeure events, cyberattacks beyond reasonable control, or failures of third-party infrastructure providers.",
			],
			subsections: [],
		},
		{
			id: "54",
			title: "INDEMNIFICATION",
			paragraphs: [
				"Business Customers agree to indemnify, defend, and hold harmless Socioknack Technologies Ltd., its directors, officers, employees, contractors, affiliates, successors, and assigns from and against any claims, liabilities, losses, damages, costs, fines, penalties, or expenses (including reasonable legal fees) arising from:",
				"This indemnity shall survive termination of the Services to the extent permitted by law",
			],
			bullets: [
				"unlawful collection of Personal Data by the Business Customer;",
				"failure to obtain required consents;",
				"unlawful instructions provided to Socioknack;",
				"breach of applicable privacy laws by the Business Customer;",
				"misuse of the Services;",
				"infringement of third-party rights through Customer Data.",
			],
			subsections: [],
		},
		{
			id: "55",
			title: "FORCE MAJEURE",
			paragraphs: [
				"Socioknack shall not be liable for any delay or failure to perform its obligations under this Privacy Policy where such delay or failure results from circumstances beyond its reasonable control, including but not limited to:",
				"Performance shall resume as soon as reasonably practicable following the cessation of the force majeure event.",
			],
			bullets: [
				"acts of God;",
				"natural disasters;",
				"epidemics or pandemics;",
				"war;",
				"terrorism;",
				"civil unrest;",
				"labour disputes;",
				"governmental actions;",
				"internet disruptions;",
				"telecommunications failures;",
				"cyber incidents affecting critical infrastructure;",
				"widespread power outages.",
			],
			subsections: [],
		},
		{
			id: "56",
			title: "AMENDMENTS TO THIS PRIVACY POLICY",
			paragraphs: [
				"Socioknack reserves the right to amend, revise, update, or replace this Privacy Policy at any time to reflect:",
				"Material changes will be communicated through one or more of the following methods:",
				'The "Last Updated" date at the beginning of this Policy will indicate the effective version.',
				"Continued use of the Services after the effective date of an amended Privacy Policy constitutes acceptance of the revised Policy",
			],
			bullets: [
				"changes in legislation;",
				"regulatory guidance;",
				"technological developments;",
				"platform enhancements;",
				"changes to business operations;",
				"security improvements.",
				"publication on the Platform;",
				"email notification;",
				"in-application notices;",
				"website announcements.",
			],
			subsections: [],
		},
		{
			id: "57",
			title: "GOVERNING LAW",
			paragraphs: [
				"This Privacy Policy shall be governed by and construed in accordance with the laws of the Federal Republic of Nigeria, without regard to conflict of law principles.",
				"Where mandatory provisions of another applicable jurisdiction apply to specific processing activities, Socioknack shall comply with those mandatory requirements to the extent legally required.",
			],
			bullets: [],
			subsections: [],
		},
		{
			id: "58",
			title: "DISPUTE RESOLUTION",
			paragraphs: [
				"The parties shall endeavour to resolve any dispute arising out of or relating to this Privacy Policy through good-faith negotiations.",
				"If a dispute cannot be resolved amicably within thirty (30) days, the parties may refer the dispute to mediation before commencing formal legal proceedings.",
				"Nothing in this section prevents either party from seeking urgent injunctive or equitable relief where necessary to protect confidential information, intellectual property, or data security.",
			],
			bullets: [],
			subsections: [],
		},
		{
			id: "59",
			title: "SEVERABILITY",
			paragraphs: [
				"If any provision of this Privacy Policy is held to be invalid, unlawful, or unenforceable by a court or competent authority, that provision shall be deemed severed to the minimum extent necessary, and the remaining provisions shall continue in full force and effect.",
			],
			bullets: [],
			subsections: [],
		},
		{
			id: "60",
			title: "ENTIRE PRIVACY POLICY",
			paragraphs: [
				"This Privacy Policy constitutes the entire understanding between Socioknack and Users with respect to the processing of Personal Data, except where supplemented by:",
			],
			bullets: [
				"Data Processing Agreements;",
				"Enterprise Subscription Agreements;",
				"Service Level Agreements;",
				"Terms of Use;",
				"End User Licence Agreements; or",
				"other written agreements executed by the parties.",
			],
			subsections: [],
		},
		{
			id: "61",
			title: "CONTACT INFORMATION",
			paragraphs: [
				"Questions, requests, or concerns regarding this Privacy Policy may be directed to:",
				"Socioknack Ltd.",
				"Privacy Office",
				"Email: info@socioknack.com",
				"Website: www.socioknack.com",
				'Where a Data Protection Officer ("DPO") has been appointed, additional contact information shall be published on the Socioknack website.',
			],
			bullets: [],
			subsections: [],
		},
		{
			id: "ANNEX A",
			title: "COOKIE CATEGORIES",
			paragraphs: [
				"Socioknack may utilise the following categories of cookies:",
				"A detailed Cookie Policy may be published separately and shall supplement this Privacy Policy.",
			],
			bullets: [
				"Essential Cookies",
				"Authentication Cookies",
				"Session Cookies",
				"Security Cookies",
				"Preference Cookies",
				"Analytics Cookies",
				"Performance Cookies",
				"Functional Cookies",
			],
			subsections: [],
		},
		{
			id: "ANNEX B",
			title: "DATA RETENTION SUMMARY",
			paragraphs: [
				"Socioknack maintains internal retention schedules that categorise information according to business purpose, legal obligations, contractual requirements, and security considerations.",
				"Upon expiration of the applicable retention period, Personal Data shall be securely deleted, anonymised, or archived in accordance with applicable law.",
			],
			bullets: [],
			subsections: [],
		},
		{
			id: "ANNEX C",
			title: "INFORMATION SECURITY CONTROLS",
			paragraphs: [
				"Socioknack's security framework may include:",
				"Security controls are reviewed periodically and may evolve to address emerging threats.",
			],
			bullets: [
				"Encryption of data in transit;",
				"Encryption of sensitive credentials;",
				"Role-based access control;",
				"Multi-factor authentication (where enabled);",
				"Audit logging;",
				"Secure cloud hosting;",
				"Vulnerability assessments;",
				"Penetration testing;",
				"Security awareness training;",
				"Incident response procedures;",
				"Disaster recovery planning;",
				"Business continuity measures.",
			],
			subsections: [],
		},
		{
			id: "ANNEX D",
			title: "DATA SUBJECT REQUEST PROCEDURE",
			paragraphs: [
				"Individuals wishing to exercise privacy rights may submit a written request to the Privacy Office.",
				"Requests should include sufficient information to verify identity and identify the information requested.",
				"Socioknack shall respond within the timeframe required by applicable law, subject to any lawful extensions.",
				"Where a request cannot be fulfilled, Socioknack shall provide reasons where legally permissible.",
			],
			bullets: [],
			subsections: [],
		},
		{
			id: "ACCEPTANCE",
			title: "ACCEPTANCE",
			paragraphs: [
				"By creating an account, accessing, or using the Socioknack Platform, you acknowledge that:",
			],
			bullets: [
				"You have read and understood this Privacy Policy.",
				"You agree to the collection, use, disclosure, and processing of Personal Data as described herein.",
				"You understand your rights under applicable data protection legislation.",
				"You agree to comply with all applicable obligations relating to the use of the Services.",
			],
			subsections: [],
		},
	],
};
