export interface TermsSection {
	id: string;
	title: string;
	paragraphs: string[];
	bullets: string[];
}

export interface TermsData {
	title: string;
	version: string;
	sections: TermsSection[];
	acceptance: string;
}

export const termsAndConditions: TermsData = {
	title: "SOCIOKNACK LTD. TERMS AND CONDITIONS OF USE",
	version: "Version: 1.0 Enterprise Edition",
	acceptance:
		"By accessing or using the Socioknack Platform, you acknowledge that you have read, understood, and agreed to be bound by these Terms and Conditions.",
	sections: [
		{
			id: "1",
			title: "INTRODUCTION",
			paragraphs: [
				'These Terms and Conditions ("Terms") constitute a legally binding agreement between Socioknack Technologies Ltd. ("Socioknack", "we", "our", or "us") and every individual or entity ("User", "Customer", "Business Customer", "you", or "your") that accesses or uses the Socioknack website, mobile applications, software platform, APIs, dashboards, and related services (collectively, the "Services").',
				"By creating an account, accessing, or using the Services, you acknowledge that you have read, understood, and agreed to be bound by these Terms.",
				"If you do not agree with these Terms, you must not access or use the Services.",
			],
			bullets: [],
		},
		{
			id: "2",
			title: "DEFINITIONS",
			paragraphs: ["For the purposes of these Terms:"],
			bullets: [
				"Account: a registered user profile created to access the Platform.",
				"Administrator: an authorised individual responsible for managing an organisation's Socioknack workspace.",
				"Authorised User: an individual permitted by a Business Customer to access the Platform.",
				"Business Customer: any company, organisation, institution, or entity subscribing to the Services.",
				"Business Data: organisational information uploaded into the Platform, including sales data, customer records, territories, reports, commission structures, and analytics.",
				"Customer Data: information uploaded or generated by a Business Customer through use of the Platform.",
				"Platform: the Socioknack web application, mobile applications, APIs, databases, dashboards, software, and associated technologies.",
				"Subscription: the commercial plan purchased by a Business Customer to access the Platform.",
			],
		},
		{
			id: "3",
			title: "ELIGIBILITY",
			paragraphs: [
				"To use the Services, you represent and warrant that:",
				"Socioknack reserves the right to refuse registration or suspend accounts where eligibility requirements are not satisfied.",
			],
			bullets: [
				"You are at least 18 years of age or have the legal capacity to enter into binding contracts.",
				"You have authority to bind the organisation you represent.",
				"The information you provide during registration is accurate and complete.",
				"You will promptly update your information where it changes.",
			],
		},
		{
			id: "4",
			title: "ACCOUNT REGISTRATION",
			paragraphs: [
				"Users are responsible for maintaining the confidentiality of their login credentials.",
				"You agree to:",
				"Socioknack reserves the right to suspend accounts where fraudulent or suspicious activities are detected.",
			],
			bullets: [
				"Maintain accurate account information.",
				"Keep your password secure.",
				"Notify Socioknack immediately of any suspected unauthorised access.",
				"Accept responsibility for all activities conducted through your account unless such activities result solely from Socioknack's negligence or security breach.",
			],
		},
		{
			id: "5",
			title: "LICENCE TO USE THE PLATFORM",
			paragraphs: [
				"Subject to compliance with these Terms and payment of applicable subscription fees, Socioknack grants you a limited, non-exclusive, non-transferable, non-sublicensable, and revocable licence to access and use the Services solely for your internal business operations.",
				"This licence does not transfer ownership of the Platform or any intellectual property rights.",
			],
			bullets: [],
		},
		{
			id: "6",
			title: "ACCEPTABLE USE",
			paragraphs: [
				"You agree to use the Platform only for lawful purposes.",
				"You shall not:",
				"Violation of this section may result in immediate suspension or termination of your account.",
			],
			bullets: [
				"Upload malicious software or viruses.",
				"Attempt to gain unauthorised access to the Platform.",
				"Reverse engineer or decompile the software.",
				"Copy, reproduce, distribute, or resell the Platform without written authorisation.",
				"Use the Platform for fraudulent, unlawful, or deceptive purposes.",
				"Interfere with the security, integrity, or availability of the Services.",
				"Upload unlawful, defamatory, or infringing content.",
			],
		},
		{
			id: "7",
			title: "SUBSCRIPTIONS, FEES, AND PAYMENTS",
			paragraphs: [
				"Access to certain Services may require payment of subscription fees.",
				"By subscribing, you agree to:",
				"Failure to pay subscription fees may result in suspension or termination of access.",
				"Unless otherwise agreed in writing, subscription fees are non-refundable.",
			],
			bullets: [
				"Pay all applicable fees in accordance with your selected plan.",
				"Provide accurate billing information.",
				"Pay applicable taxes unless otherwise stated.",
			],
		},
		{
			id: "8",
			title: "CUSTOMER DATA",
			paragraphs: [
				"Business Customers retain ownership of all Customer Data uploaded to the Platform.",
				"By using the Services, you grant Socioknack a limited right to process, store, transmit, back up, and analyse Customer Data solely for the purpose of providing the Services.",
				"You warrant that:",
			],
			bullets: [
				"You have lawful authority to upload Customer Data.",
				"Customer Data does not infringe any third-party rights.",
				"Customer Data complies with applicable laws and regulations.",
			],
		},
		{
			id: "9",
			title: "INTELLECTUAL PROPERTY",
			paragraphs: [
				"All intellectual property rights in the Platform, including software, source code, trademarks, logos, documentation, graphics, APIs, databases, and technology, remain the exclusive property of Socioknack Technologies Ltd. or its licensors.",
				"Nothing in these Terms transfers ownership of any intellectual property rights to you.",
			],
			bullets: [],
		},
		{
			id: "10",
			title: "SERVICE AVAILABILITY",
			paragraphs: [
				"Socioknack will use commercially reasonable efforts to maintain the availability of the Services.",
				"However, the Platform may be temporarily unavailable due to:",
				"Socioknack does not guarantee uninterrupted or error-free operation.",
			],
			bullets: [
				"Scheduled maintenance;",
				"Emergency maintenance;",
				"Internet outages;",
				"Third-party service interruptions;",
				"Events beyond our reasonable control.",
			],
		},
		{
			id: "11",
			title: "PRIVACY",
			paragraphs: [
				"Your use of the Services is subject to the Socioknack Privacy Policy, which explains how Personal Data is collected, used, stored, and protected.",
				"By using the Services, you acknowledge that you have read and accepted the Privacy Policy.",
			],
			bullets: [],
		},
		{
			id: "12",
			title: "THIRD-PARTY SERVICES",
			paragraphs: [
				"The Platform may integrate with third-party applications, payment gateways, communication platforms, or cloud services.",
				"Socioknack is not responsible for the availability, functionality, or privacy practices of third-party services.",
				"Your use of third-party services is governed by their respective terms and policies.",
			],
			bullets: [],
		},
		{
			id: "13",
			title: "SUSPENSION AND TERMINATION",
			paragraphs: [
				"Socioknack may suspend or terminate your access to the Services where:",
				"Termination does not affect accrued rights or obligations existing before termination.",
			],
			bullets: [
				"You breach these Terms;",
				"Subscription fees remain unpaid;",
				"Fraudulent or unlawful activities are suspected;",
				"Continued access poses a security risk;",
				"Required by law or regulatory authority.",
			],
		},
		{
			id: "14",
			title: "DISCLAIMER OF WARRANTIES",
			paragraphs: [
				'Except as expressly stated, the Services are provided "as is" and "as available."',
				"To the fullest extent permitted by law, Socioknack disclaims all implied warranties, including warranties of merchantability, fitness for a particular purpose, non-infringement, and uninterrupted availability.",
			],
			bullets: [],
		},
		{
			id: "15",
			title: "LIMITATION OF LIABILITY",
			paragraphs: [
				"To the maximum extent permitted by applicable law:",
				"Nothing in these Terms excludes liability where exclusion is prohibited by law.",
			],
			bullets: [
				"Socioknack shall not be liable for indirect, incidental, consequential, or punitive damages.",
				"Socioknack shall not be liable for loss of profits, business interruption, or loss of data arising from use of the Services.",
			],
		},
		{
			id: "16",
			title: "INDEMNIFICATION",
			paragraphs: [
				"You agree to indemnify and hold harmless Socioknack Technologies Ltd., its directors, officers, employees, contractors, affiliates, and agents from claims, losses, damages, liabilities, costs, or expenses arising from:",
			],
			bullets: [
				"Your breach of these Terms;",
				"Your misuse of the Services;",
				"Your violation of applicable law;",
				"Your infringement of third-party rights.",
			],
		},
		{
			id: "17",
			title: "FORCE MAJEURE",
			paragraphs: [
				"Socioknack shall not be liable for failure or delay in performing its obligations where such failure results from events beyond its reasonable control, including natural disasters, cyber incidents, power failures, governmental actions, pandemics, labour disputes, or internet disruptions.",
			],
			bullets: [],
		},
		{
			id: "18",
			title: "GOVERNING LAW AND DISPUTE RESOLUTION",
			paragraphs: [
				"These Terms shall be governed by the laws of the Federal Republic of Nigeria.",
				"The parties shall first seek to resolve disputes through good-faith negotiations.",
				"Where a dispute cannot be resolved amicably, it shall be submitted to the competent courts of Nigeria unless otherwise agreed in writing.",
			],
			bullets: [],
		},
		{
			id: "19",
			title: "AMENDMENTS",
			paragraphs: [
				"Socioknack reserves the right to amend these Terms from time to time.",
				"Material changes will be communicated through the Platform, email, or the Socioknack website.",
				"Continued use of the Services after the effective date of any amendment constitutes acceptance of the revised Terms.",
			],
			bullets: [],
		},
		{
			id: "20",
			title: "SEVERABILITY",
			paragraphs: [
				"If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.",
			],
			bullets: [],
		},
		{
			id: "21",
			title: "ENTIRE AGREEMENT",
			paragraphs: [
				"These Terms, together with the Socioknack Privacy Policy, Service Level Agreement (where applicable), Data Processing Agreement (where applicable), and any executed subscription agreement, constitute the entire agreement between the parties regarding the use of the Services.",
			],
			bullets: [],
		},
		{
			id: "22",
			title: "CONTACT INFORMATION",
			paragraphs: [
				"For questions regarding these Terms and Conditions, please contact:",
				"Socioknack Technologies Ltd.\nEmail: info@socioknack.com\nWebsite: www.socioknack.com",
			],
			bullets: [],
		},
	],
};
